<?php

namespace Tests\Application\Service\SafeBox;

use SafeBox\Application\Service\SafeBox\PasswordValidator;
use SafeBox\Infrastructure\Repository\SafeBox\FileCommonPasswordRepository;
use Tests\TestCase;

class PasswordValidatorTest extends TestCase
{
    /**
     * @var PasswordValidator
     */
    private $safeBoxPassword;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->safeBoxPassword = new PasswordValidator(new FileCommonPasswordRepository());
    }

    public function test_password_throws_minim_length_exception()
    {
        $this->expectException(\SafeBox\Application\Service\SafeBox\TooShortPasswordException::class);
        $password = 12345;
        $this->safeBoxPassword->validateStrength($password);
    }


    public function test_new_password_throws_common_password_exception()
    {
        $this->expectException(\SafeBox\Application\Service\SafeBox\CommonPasswordException::class);
        $password = 123456;
        $this->safeBoxPassword->validateStrength($password);
    }
}
